# Carrix Production
name: Carrix-production

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select environment'
        required: true
        type: choice
        options:        
          - production
      working_directory:
        description: 'Terraform directory path'
        required: true
        default: '.'
        type: string
jobs:
  # Production Job
  Prod-Deployment:
    if: github.event.inputs.target_env == 'production'
    uses: ./.github/workflows/terraform-template-multi.yml
    with:
      environment: 'production'
      working_directory: ${{ github.event.inputs.working_directory }}
      tf_state_key: 'prod.terraform.tfstate'
    secrets:
      client_id: ${{ secrets.CLIENT_ID_JO_APNE_SETTINGS_ME_RAKHA_HAI }}
      subscription_id: ${{ secrets.SUB_ID_SETTINGS_VALA }}
      tenant_id: ${{ secrets.TENANT_ID_SETTINGS_VALA }}
      resource_group_name: ${{ secrets.RG_NAME }}
      storage_account_name: ${{ secrets.STORAGE_ACCOUNT }}
      container_name: ${{ secrets.CONTAINER_NAME }}  
