name: Multi-Env Infra Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  

 
  # Production Environment
  Production-Deployment:
    uses: ./.github/workflows/terraform-template.yml
    with:
      environment: 'Production'
      client_id: 'PROD_APP_ID'
      subscription_id: 'SUBSCRIPTION_ID'
      tenant_id: 'TENANT_ID'
      resource_group_name: 'myrg'

  
