# Carrix uat env
name: Multi-Env Infra Pipeline

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - sit
          - uat
          - prod
      working_directory:
        description: 'Terraform directory path'
        required: true
        default: '.'
        type: string
jobs:
  # UAT Job
  UAT-Deployment:
    if: github.event.inputs.target_env == 'uat'
    uses: ./.github/workflows/terraform-template-multi.yml
    with:
      environment: 'uat'
      working_directory: ${{ github.event.inputs.working_directory }}
      tf_state_key: 'uat.terraform.tfstate'
    secrets: inherit
