name: Multi-Env Infra Pipeline

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Terraform files ki directory path dalein (e.g. ./infra/prod)'
        required: true
        default: '.'
        type: string

jobs:  
  Production-Deployment:      
    uses: ./.github/workflows/terraform-temp-first.yml
    with:
      environment: 'production' 
      working_directory: ${{ github.event.inputs.working_directory }}
      tf_state_key: 'prod.terraform.tfstate'
    secrets: 
      client_id: ${{ secrets.CLIENT_ID }}
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      tenant_id: ${{ secrets.TENANT_ID }}
      resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
      storage_account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      container_name: ${{ secrets.CONTAINER_NAME }}
