name: Multi-Env Infra Pipeline

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch: 

jobs:  
  Production-Deployment:      
    uses: ./.github/workflows/terraform-template.yml
    with:
      environment: 'Production' 
      working_directory: '.' 
      client_id: ${{ secrets.CLIENT_ID }}
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      tenant_id: ${{ secrets.TENANT_ID }}
      resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
      storage_account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      container_name: ${{ secrets.CONTAINER_NAME }}
      tf_state_key: 'prod.terraform.tfstate'
